steps:
  - id: "Executando testes"
    name: "gcr.io/cloud-builders/go"
    args: ["test", "-v", "message"]
    env: ["GO_PATH=/src"]

  - id: "Construindo app"
    name: "gcr.io/cloud-builders/go"
    args: ["build", "./src/main.go"]
    env: ["GOOS=linux"]

  - id: "Criando container"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "evertoncorrea/go-rocks"
      - "."

  - id: "Pushing image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/go-rocks:$SHORT_SHA"]

  - id: "Adjusting deployment file - k8s"
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "/bin/sh"
    args:
      - "-c"
      - |
        sed 's#img-deployment#gcr.io/$PROJECT_ID/go-rocks:$SHORT_SHA#global' k8s/deployment.yaml > k8s/deployment-new.yaml
        cat k8s/deployment-new.yaml;

  - id: "Deploying k8s"
    name: "gcr.io/cloud-builders/kubectl"
    args:
      - "apply"
      - "-f"
      - "k8s/deployment-new.yaml"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-c"
      - "CLOUDSDK_CONTAINER_CLUSTER=my-first-cluster-1"
