apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-rocks
spec:
  selector:
    matchLabels:
      app: go-rocks

  template:
    metadata:
      labels:
        app: go-rocks
    spec:
      containers:
        - image: "img-deployment"
          name: go-rocks
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
            limits:
              cpu: "100m"
