apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: go-rocks
spec:
  maxReplicas: 6
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-rocks
  targetCPUUtilizationPercentage: 15
